service: 
  name: currence-backend
  profile: currence-admin
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    TOKEN_SECRET: PragueOkaikweiTeriPetrolulAwful
    CURRENCE_USERS_TABLE: CURRENCE_USERS # ${self:service}-${opt:stage, self:provider.stage}
    CURRENCE_STATUSES_TABLE: CURRENCE_STATUSES # ${self:service}-${opt:stage, self:provider.stage}
    CURRENCE_FEEDS_TABLE: CURRENCE_FEEDS # ${self:service}-${opt:stage, self:provider.stage}
    CURRENCE_STORIES_TABLE: CURRENCE_STORIES
    CURRENCE_FOLLOWS_TABLE: CURRENCE_FOLLOWS
    FEED_UPDATE_QUEUE: FeedUpdateQueue
    FETCH_FOLLOWERS_QUEUE: FetchFollowersQueue
    SQS_URL_UPDATE_FEED: "https://sqs.us-east-1.amazonaws.com/454900433813/FeedUpdateQueue"
    SQS_URL_FETCH_FOLLOWERS: "https://sqs.us-east-1.amazonaws.com/454900433813/FetchFollowersQueue"




  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchGet
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:454900433813:table/CURRENCE_USERS"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchGet
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CURRENCE_STATUSES_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchWriteItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchGet
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CURRENCE_STORIES_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
        - dynamodb:BatchGet
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CURRENCE_FEEDS_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchGet
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CURRENCE_FOLLOWS_TABLE}"
    - Effect: Allow
      Action:
        - sqs:DeleteMessage
        - sqs:ReceiveMessage
        - sqs:SendMessage
      Resource: "arn:aws:sqs:${self:provider.region}:454900433813:${self:provider.environment.FEED_UPDATE_QUEUE}"
    - Effect: Allow
      Action:
        - sqs:DeleteMessage
        - sqs:ReceiveMessage
        - sqs:SendMessage
      Resource: "arn:aws:sqs:${self:provider.region}:454900433813:${self:provider.environment.FETCH_FOLLOWERS_QUEUE}"

functions:
  test:
    handler: ./functions/util/test.test
  signin:
    handler: ./functions/auth/signin.signin
    description: Signs a user into the app
    events:
      - http:
          method: post
          cors: true # <-- CORS!
          path: signin
          request:
            passThrough: WHEN_NO_TEMPLATES
  signup:
    handler: ./functions/auth/signup.signup
    description: Signs a new user up for the app
    events:
      - http:
          method: post
          cors: true # <-- CORS!
          path: signup
          request:
            passThrough: WHEN_NO_TEMPLATES
  getUser:
    handler: ./functions/util/getUser.getUser
    description: Gets user
    events:
      - http:
          method: get 
          cors: true # <-- CORS!
          path: user
          request:
            passThrough: WHEN_NO_TEMPLATES
  getFeed:
    handler: ./functions/feed/index.getFeed
    description: Gets feed of a user
    events:
      - http:
          method: get
          cors: true # <-- CORS!
          path: feed
          request:
            passThrough: WHEN_NO_TEMPLATES
  getStory:
    handler: ./functions/story/index.getStory
    description: Gets story of a user
    events:
      - http:
          method: get
          cors: true # <-- CORS!
          path: story
          request:
            passThrough: WHEN_NO_TEMPLATES
  getFollowers:
    handler: ./functions/followers/index.getFollowers
    description: Gets a users followers
    events:
      - http:
          method: get
          cors: true # <-- CORS!
          path: followers
          request:
            passThrough: WHEN_NO_TEMPLATES
  getFollowing:
    handler: ./functions/following/index.getFollowing
    description: Gets following of a user
    events:
      - http:
          method: get
          cors: true # <-- CORS!
          path: following
          request:
            passThrough: WHEN_NO_TEMPLATES
  follow:
    handler: ./functions/follow/index.follow
    description: Follow a user.
    events:
      - http:
          method: post
          cors: true # <-- CORS!
          path: follow
          request:
            passThrough: WHEN_NO_TEMPLATES
  unfollow:
    handler: ./functions/unfollow/index.unfollow
    description: Unfollow a user. 
    events:
      - http:
          method: post
          cors: true # <-- CORS!
          path: unfollow
          request:
            passThrough: WHEN_NO_TEMPLATES
  isFollowing:
    handler: ./functions/util/isFollowing.isFollowing
    description: Returns a boolean indicating whether a user is a follower of another user
    events:
      - http:
          method: get
          cors: true # <-- CORS!
          path: isFollowing
          request:
            passThrough: WHEN_NO_TEMPLATES
  createStatus:
    handler: ./functions/status/createStatus.createStatus
    description: Creates a status.
    events:
      - http:
          method: post
          cors: true # <-- CORS!5
          path: status
          request:
            passThrough: WHEN_NO_TEMPLATES
  isValidAlias:
    handler: ./functions/util/isValidAlias.isValidAlias
    description: Returns a boolean indicating whether an alias is valid or not
    events:
      - http:
          method: get
          cors: true # <-- CORS!
          path: alias
          request:
            passThrough: WHEN_NO_TEMPLATES
  receiveStatus:
    handler: ./services/SQS.receiveStatus
    events:
      - sqs: 	
          arn: "arn:aws:sqs:${self:provider.region}:454900433813:${self:provider.environment.FEED_UPDATE_QUEUE}"
          batchSize: 1
  receiveFollowers:
    handler: ./services/SQS.receiveFollowers
    events:
      - sqs: 	
          arn: "arn:aws:sqs:${self:provider.region}:454900433813:${self:provider.environment.FETCH_FOLLOWERS_QUEUE}"
          batchSize: 1




    #             FEED_UPDATE_QUEUE: FeedUpdateQueue
    # FETCH_FOLLOWERS_QUEUE: FetchFollowersQueue
    # SQS_URL_UPDATE_FEED: "https://sqs.us-east-1.amazonaws.com/454900433813/FeedUpdateQueue"
    # SQS_URL_FETCH_FOLLOWERS: "https://sqs.us-east-1.amazonaws.com/454900433813/FetchFollowersQueue"
# resources:
#   Resources:
#     CurrenceUsersTable:
#       Type: AWS::DynamoDB::Table
#       DeletionPolicy: Retain # Keeps around the DynamoDB resource when we redeploy/destroy
#       Properties:
#         AttributeDefinitions:
#           -
#             AttributeName: id
#             AttributeType: S
#           - 
#             AttributeName: alias
#             AttributeType: S
#           - 
#             AttributeName: password
#             AttributeType: S
#           - 
#             AttributeName: picture
#             AttributeType: S
#         KeySchema:
#           -
#             AttributeName: id
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
#         TableName: ${self:provider.environment.CURRENCE_USERS_TABLE}
#     CurrenceStatusesTable:
#       Type: AWS::DynamoDB::Table
#       DeletionPolicy: Retain # Keeps around the DynamoDB resource when we redeploy/destroy
#       Properties:
#         AttributeDefinitions:
#           -
#             AttributeName: id
#             AttributeType: S
#           - 
#             AttributeName: alias
#             AttributeType: S
#         KeySchema:
#           -
#             AttributeName: id
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
#         TableName: ${self:provider.environment.CURRENCE_STATUSES_TABLE}