service:
  name: currence-backend
  profile: currence-admin
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  signin:
    handler: ./functions/auth/index.signin
    description: Submit alias and password, return auth token
    events:
      - http:
          method: post
          cors: true # <-- CORS!
          path: signin
          request:
            passThrough: WHEN_NO_TEMPLATES
  getFeed:
    handler: ./functions/feed/index.getFeed
    description: Gets feed of user
    events:
      - http:
          method: post
          cors: true # <-- CORS!
          path: getFeed
          request:
            passThrough: WHEN_NO_TEMPLATES
  # signup:
  #   handler: handler.signin
  #   events:
  #     - http:
  #         path: signup
  #         cors: true
  #         integration: lambda
  #         method: post
  #         authorizer:
  #           arn: "arn:aws:cognito-idp:us-east-1:454900433813:userpool/us-east-1_q6Ry6izzy"
  #           # claims:
  #           #   - email
